#!/sbin/busybox sh
exec > /dev/null 2>&1
export PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin

/sbin/busybox mount -o remount rw /system
/sbin/busybox echo "" >> /lupus.log
/sbin/busybox echo "[INIT.D] Checking if device supports init.d" >> /lupus.log
# make init.d directory
/sbin/busybox echo "[*] Creating init.d directory" >> /lupus.log
/sbin/busybox mkdir -p /system/etc/init.d

/sbin/busybox echo "[*] Setting init.d permissions" >> /lupus.log
# set permissions on init.d folder
/sbin/busybox chmod -R 0777 /system/etc/init.d/* > /dev/null 2>&1
/sbin/busybox mount -o remount ro /system

/system/bin/logwrapper /sbin/busybox run-parts /system/etc/init.d

/sbin/busybox echo "[*] Init.d set.." >> /lupus.log

