#!/system/bin/sh

if [ -e /system/lib/modules/frandom.ko ]; then
       insmod /system/lib/modules/frandom.ko
       
       if [ -e /dev/frandom ] && [ "`lsmod | grep ^frandom`" ]; then

               chmod 644 /dev/frandom
               mv /dev/random /dev/random.ori
               mv /dev/urandom /dev/urandom.ori
               ln /dev/frandom /dev/random
               chmod 644 /dev/random
               ln /dev/frandom /dev/urandom
               chmod 644 /dev/urandom
       fi
fi



